AWSTemplateFormatVersion: 2010-09-09
Description: Launch a simple ec2 instance
Resources:
  Instance1:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-1b791862
      InstanceType: t2.micro
